export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";
export const ADD_ITEMS = "ADD_ITEMS";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const FAVORITE_ITEM = "FAVORITE_ITEM";
export const REMOVE_FAVORITE_ITEM = "REMOVE_FAVORITE_ITEM";
export const TOGGLE_THEME = "TOGGLE_THEME";
